### ISSUE TITLE
Translated commands

### ISSUE THREAD

**Issue by Burwellian** [FuelRats/pipsqueak#59] opened 2016-02-12 22:14 UTC
Add translated versions of commands such as !prep (as E.G. !prep-de to translate to German) for clients who struggle to speak English. Russian prob most needed.

**Comment by dewiniaid** [comment] 2016-02-12 22:52
#49 adds a version of this.

**Comment by dewiniaid** [comment] 2016-02-19 16:57
Closing as a duplicate of #40

**Closed as completed by dewiniaid** 2016-02-19 16:57 UTC
