### ISSUE TITLE
!sys bug

### ISSUE THREAD

**Issue by stehx26** [FuelRats/pipsqueak#137] opened 2016-08-17 21:18 UTC
Doesn't overwrite original system location in paperwork

Note from Kilo363
found a PW issue, don't know if it's known or not. Last rescue the system was corrected during the rescue, and bot updated by dispatch. When generting sys name in pw it still showed the original name given in the r@ts1gn@l

**Comment by Marenthyu** [comment] 2016-08-17 21:29
Can't reproduce.

**Comment by Marenthyu** [comment] 2016-08-17 22:12
couldnt reproduce with kilo, closing as unreproducable for now.

**Closed as completed by Marenthyu** 2016-08-17 22:12 UTC
